# ???????????????????
# JDBC URL ???jdbc:mysql://127.0.0.1:3306/studentoperation?useSSL=false&serverTimezone=UTC

jdbc.url=jdbc:mysql://127.0.0.1:3306/studentoperation
jdbc.username=root
jdbc.password=111222

